name: brainy_note
description: Intelligent note-taking app for students
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.1.2
  crypto: ^3.0.3
  flutter_quill: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.6

flutter:
  uses-material-design: true
  assets:
    - assets/
